---
platform: linux

params:
  REGION:
  DEPLOYMENT_NAME:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

inputs:
- name: concourse-up-release
- name: this-repo
outputs:
- name: exported-file

run:
  path: this-repo/tasks/backup.sh
